version: '3'

# picked up from https://github.com/callicoder/go-docker-compose
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: